// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcrmptamWGgzcOctaMEB6ZezqvH9qI9R4',
    appId: '1:604016347629:web:ddd2341f44235c3823ffe4',
    messagingSenderId: '604016347629',
    projectId: 'fooddelivery-ec99a',
    authDomain: 'fooddelivery-ec99a.firebaseapp.com',
    storageBucket: 'fooddelivery-ec99a.appspot.com',
    measurementId: 'G-HPXGVBWXCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdkwECD_QZRYCP-sIjlF1soQ61625SHc',
    appId: '1:604016347629:android:d5581d4720ee5cbc23ffe4',
    messagingSenderId: '604016347629',
    projectId: 'fooddelivery-ec99a',
    storageBucket: 'fooddelivery-ec99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTKj3lB84h16nv3GeE-Jb_ffpf957AQo',
    appId: '1:604016347629:ios:240ddd0e896cdfde23ffe4',
    messagingSenderId: '604016347629',
    projectId: 'fooddelivery-ec99a',
    storageBucket: 'fooddelivery-ec99a.appspot.com',
    iosBundleId: 'com.fooddelivery.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTKj3lB84h16nv3GeE-Jb_ffpf957AQo',
    appId: '1:604016347629:ios:240ddd0e896cdfde23ffe4',
    messagingSenderId: '604016347629',
    projectId: 'fooddelivery-ec99a',
    storageBucket: 'fooddelivery-ec99a.appspot.com',
    iosBundleId: 'com.fooddelivery.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcrmptamWGgzcOctaMEB6ZezqvH9qI9R4',
    appId: '1:604016347629:web:797303196fa82c4223ffe4',
    messagingSenderId: '604016347629',
    projectId: 'fooddelivery-ec99a',
    authDomain: 'fooddelivery-ec99a.firebaseapp.com',
    storageBucket: 'fooddelivery-ec99a.appspot.com',
    measurementId: 'G-5N9Z5N6FEZ',
  );
}
